// organizations
export const ORGANIZATION_ADDED = 'ORGANIZATION_ADDED';
export const ORGANIZATIONS_FETCHED = 'ORGANIZATIONS_FETCHED';
export const ORGANIZATIONS_LOADED = 'ORGANIZATIONS_LOADED';
export const ORGANIZATION_SELECTED = 'ORGANIZATION_SELECTED';
export const SINGER_ADDED = 'SINGER_ADDED';
export const SINGERS_LOADED = 'SINGERS_LOADED';
export const ADD_SINGER_MODAL_OPENED = 'ADD_SINGER_MODAL_OPENED';
export const ADD_SINGER_MODAL_CLOSED = 'ADD_SINGER_MODAL_CLOSED';
export const DELETE_SINGER_MODAL_OPENED = 'DELETE_SINGER_MODAL_OPENED';
export const DELETE_SINGER_MODAL_CLOSED = 'DELETE_SINGER_MODAL_CLOSED';
export const SINGER_DELETED_FROM_ORGANIZATION = 'SINGER_DELETED_FROM_ORGANIZATION';
export const DELETE_SINGER_FROM_ORGANIZATION_FAILED = 'DELETE_SINGER_FROM_ORGANIZATION_FAILED';
export const ADD_ORGANIZATION_MODAL_OPENED = 'ADD_ORGANIZATION_MODAL_OPENED';
export const ADD_ORGANIZATION_MODAL_CLOSED = 'ADD_ORGANIZATION_MODAL_CLOSED';

export const ORGANIZATIONS_REQUESTED = 'ORGANIZATIONS_REQUESTED';
export const ORGANIZATIONS_RECEIVED = 'ORGANIZATIONS_RECEIVED';

// modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// user
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

// failed requests
export const ADD_SINGER_FAILED = 'ADD_SINGER_FAILED';
export const ADD_SINGER_FAILED_CLEARED = 'ADD_SINGER_FAILED_CLEARED';
export const ADD_ORGANIZATION_FAILED = 'ADD_ORGANIZATION_FAILED';
export const ADD_ORGANIZATION_FAILED_CLEARED = 'ADD_ORGANIZATION_FAILED_CLEARED';
export const FAILED_REQUESTS_CLEARED = 'FAILED_REQUESTS_CLEARED';