// organizations
export const ORGANIZATION_ADDED = 'ORGANIZATION_ADDED';
export const ORGANIZATIONS_LOADED = 'ORGANIZATIONS_LOADED';
export const ORGANIZATION_SELECTED = 'ORGANIZATION_SELECTED';
export const ORGANIZATION_TAB_SELECTED = 'ORGANIZATION_TAB_SELECTED';
export const SINGER_ADDED = 'SINGER_ADDED';
export const SINGERS_LOADED = 'SINGERS_LOADED';
export const SINGER_DELETED_FROM_ORGANIZATION = 'SINGER_DELETED_FROM_ORGANIZATION';
export const DELETE_SINGER_FROM_ORGANIZATION_FAILED = 'DELETE_SINGER_FROM_ORGANIZATION_FAILED';
export const CHOIR_SELECTED = 'CHOIR_SELECTED';
export const CHOIR_ADDED = 'CHOIR_ADDED';
export const CHOIRS_LOADED = 'CHOIRS_LOADED';
export const CHOIR_DELETED = 'CHOIR_DELETED';
export const CHOIR_EDITED = 'CHOIR_EDITED';
export const VENUE_SELECTED = 'VENUE_SELECTED';
export const VENUE_ADDED = 'VENUE_ADDED';
export const VENUES_LOADED = 'VENUES_LOADED';
export const PERFORMANCE_ADDED = 'PERFORMANCE_ADDED';

export const ORGANIZATIONS_REQUESTED = 'ORGANIZATIONS_REQUESTED';
export const ORGANIZATIONS_RECEIVED = 'ORGANIZATIONS_RECEIVED';

// singers
export const SINGERS_REQUESTED = 'SINGERS_REQUESTED';
export const SINGERS_RECEIVED = 'SINGERS_RECEIVED';

// modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// user
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

// failed requests
export const ADD_SINGER_FAILED = 'ADD_SINGER_FAILED';
export const ADD_SINGER_FAILED_CLEARED = 'ADD_SINGER_FAILED_CLEARED';
export const ADD_ORGANIZATION_FAILED = 'ADD_ORGANIZATION_FAILED';
export const ADD_ORGANIZATION_FAILED_CLEARED = 'ADD_ORGANIZATION_FAILED_CLEARED';
export const ADD_CHOIR_FAILED = 'ADD_CHOIR_FAILED';
export const ADD_CHOIR_FAILED_CLEARED = 'ADD_CHOIR_FAILED_CLEARED';
export const ADD_PERFORMANCE_FAILED = 'ADD_PERFORMANCE_FAILED';
export const EDIT_CHOIR_FAILED = 'EDIT_CHOIR_FAILED';
export const EDIT_CHOIR_FAILED_CLEARED = 'EDIT_CHOIR_FAILED_CLEARED';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD_FAILED_CLEARED = 'CHANGE_PASSWORD_FAILED_CLEARED';
export const FAILED_REQUESTS_CLEARED = 'FAILED_REQUESTS_CLEARED';

// dummySingers
export const DUMMY_SINGERS_FETCHED = 'DUMMY_SINGERS_FETCHED';
export const DUMMY_SINGERS_LOADED = 'DUMMY_SINGERS_LOADED';
export const DUMMY_SINGERS_UPDATED = 'DUMMY_SINGERS_UPDATED';
export const DUMMY_SINGERS_MOVED = 'DUMMY_SINGERS_MOVED';

// grid
export const GRID_LOADED = 'GRID_LOADED';
export const GRID_UPDATED = 'GRID_UPDATED';
export const GRID_REQUESTED = 'GRID_REQUESTED';
export const GRID_RECEIVED = 'GRID_RECEIVED';
export const SINGER_MOVED = 'SINGER_MOVED';
export const SINGER_LIST_UPDATED = 'SINGER_LIST_UPDATED';
