export const ADD_ORGANIZATION_MODAL = 'ADD_ORGANIZATION_MODAL';
export const ADD_SINGER_MODAL = 'ADD_SINGER_MODAL';
export const DELETE_SINGER_MODAL = 'DELETE_SINGER_MODAL';
export const CHANGE_PASSWORD_MODAL = 'CHANGE_PASSWORD_MODAL';